{% set name = "pynats" %}
{% set version = "0.1.2.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: "0.1.2.3"
  git_url: https://github.com/olivercliff/pynats.git

requirements:
  build:
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - pynats

about:
  home: https://github.com/olivercliff/pynats.git
  license: BSD
  license_family: BSD
  summary: Python-based network analysis for time series