# Basic statistics
.statistics.basic:
  # Covariance
  Covariance:
    labels:
      - undirected
      - nonlinear
    dependencies:
    configs:
      - estimator: EmpiricalCovariance

.statistics.distance:
  DynamicTimeWarping:
    labels:
      - undirected
      - signed
    dependencies:
    configs:
      - global_constraint: itakura

  Barycenter:
    labels:
      - signed
    depdendencies:
    configs:
      - mode: dtw
        statistic: mean

.statistics.causal:

  # Additive noise model
  AdditiveNoiseModel:
    labels:
      - signed
    dependencies:
    configs:


# Information-theoretic statistics
.statistics.infotheory:
  DirectedInfo: # No theiler window yet
    labels:
      - signed
    dependencies:
      - java
    configs:
      - estimator: gaussian

  # Transfer entropy
  TransferEntropy:
    labels:
      - test
    dependencies:
      - java
    configs:
      - estimator: kraskov
        prop_k: 4
        auto_embed_method: MAX_CORR_AIS
        k_search_max: 10
        tau_search_max: 4
        dyn_corr_excl: AUTO
  
  # Integrated information
  IntegratedInformation:
    labels:
      - test
    dependencies: 
      - octave
    configs:
      - phitype: 'star'

# statistics that analyse in the frequency-domain (see Schoegl and Supp, 2006)
.statistics.spectral:

  CoherenceMagnitude:
    labels:
      - test
    dependencies:
    configs:
      - fs: 1

  PhaseSlopeIndex:
    labels:
      - test
    dependencies:
    configs:
      - fmin: 0
        fmax: 0.5

  PhaseLagIndex:
    labels:
      - test
    dependencies:
    configs:
      - fs: 1
        statistic: max

  SpectralGrangerCausality:
      # Non-parametric Granger causality (no VAR model)
    labels:
      - test
    dependencies:
    configs:
      - method: nonparametric
        fmin: 0
        fmax: 0.5
        statistic: mean

# statistics that analyse in the wavlet-domain (only Mortlet wavelet's at the moment)
.statistics.wavelet:
  PhaseSlopeIndex:
    labels:
      - test
    dependencies:
    configs:
      - fs: 1

.statistics.misc:
  # Cointegration
  Cointegration:
    labels:
      - test
    dependencies:
    configs:
      - method: aeg
        statistic: tstat
        autolag: aic
        maxlag: 10
        trend: ct

  # Power envelope correlation
  PowerEnvelopeCorrelation:
    labels:
      - test
    dependencies:
    configs:
      - orth: False
        log: False
        absolute: False