# Basic statistics
.statistics.basic:

  # Covariance
  covariance:
    - estimator: EmpiricalCovariance
    - estimator: EllipticEnvelope
    - estimator: GraphicalLasso
    - estimator: GraphicalLassoCV
    - estimator: LedoitWolf
    - estimator: MinCovDet
    - estimator: OAS
    - estimator: ShrunkCovariance
    - estimator: EmpiricalCovariance
      squared: True
    - estimator: EllipticEnvelope
      squared: True
    - estimator: GraphicalLasso
      squared: True
    - estimator: GraphicalLassoCV
      squared: True
    - estimator: LedoitWolf
      squared: True
    - estimator: MinCovDet
      squared: True
    - estimator: OAS
      squared: True
    - estimator: ShrunkCovariance
      squared: True

  # Precision
  precision:
    - estimator: EmpiricalCovariance
    - estimator: EllipticEnvelope
    - estimator: GraphicalLasso
    - estimator: GraphicalLassoCV
    - estimator: LedoitWolf
    - estimator: MinCovDet
    - estimator: OAS
    - estimator: ShrunkCovariance
    - estimator: EmpiricalCovariance
      squared: True
    - estimator: EllipticEnvelope
      squared: True
    - estimator: GraphicalLasso
      squared: True
    - estimator: GraphicalLassoCV
      squared: True
    - estimator: LedoitWolf
      squared: True
    - estimator: MinCovDet
      squared: True
    - estimator: OAS
      squared: True
    - estimator: ShrunkCovariance
      squared: True

  # Spearman's correlation coefficient
  spearmanr:
    - squared: True

    - squared: False

  # Kendall's rank correlation coefficient
  kendalltau:
    - squared: True

    - squared: False

  # statistics based on cross-correlation (squared means we square the xcorr, not the output)
  xcorr:
    - statistic: 'max'

    - statistic: 'max'
      squared: True
  
    - statistic: 'mean'

    - statistic: 'mean'
      squared: True

    - statistic: 'mean'
      sigonly: False

    - statistic: 'mean'
      squared: True
      sigonly: False

.statistics.distance:

  # Distance correlation
  dcorr:
    - biased: False
    - biased: True

  # Multi-scale graph correlation
  mgc:

  # Hilbert-Schmidt independence criterion
  hsic:
    - biased: False
    - biased: True

  # Heller-Heller-Gorfine (HHG) test  
  hhg:


  # Multi-scale graph correlation for time series
  mgcx:
    - max_lag: 1
    - max_lag: 10

  # Distance correlation for time series
  dcorrx:
    - max_lag: 1
    - max_lag: 10

  dynamic_time_warping:
    - global_constraint: null
    - global_constraint: itakura
    - global_constraint: sakoe_chiba

  soft_dynamic_time_warping:
    - global_constraint: null
    - global_constraint: itakura
    - global_constraint: sakoe_chiba

  canonical_time_warping:
    - global_constraint: null
    - global_constraint: itakura
    - global_constraint: sakoe_chiba
  
  longest_common_subsequence:
    - global_constraint: null
    - global_constraint: itakura
    - global_constraint: sakoe_chiba

  global_alignment_kernel:

  lb_keogh:

  barycenter:
  - mode: euclidean
    statistic: mean
  - mode: euclidean
    statistic: max
  - mode: dtw
    statistic: mean
  - mode: dtw
    statistic: max
  - mode: sgddtw
    statistic: mean
  - mode: sgddtw
    statistic: max
  - mode: softdtw
    statistic: mean
  - mode: softdtw
    statistic: max

  - mode: euclidean
    statistic: mean
    squared: True

  - mode: euclidean
    statistic: max
    squared: True

  - mode: dtw
    statistic: mean
    squared: True

  - mode: dtw
    statistic: max
    squared: True

  - mode: sgddtw
    statistic: mean
    squared: True

  - mode: sgddtw
    statistic: max
    squared: True

  - mode: softdtw
    statistic: mean
    squared: True

  - mode: softdtw
    statistic: max
    squared: True

.statistics.causal:

  # Additive noise model
  anm:

  # Conditional distribution similarity statistic
  cds:

  # Regression error-based causal inference
  reci:

  # Information-geometric conditional independence
  igci:

  # Convergent-cross mapping
  ccm:
    - statistic: mean
    - statistic: max
    - statistic: diff
    - statistic: mean
      embedding_dimension: 1
    - statistic: max
      embedding_dimension: 1
    - statistic: diff
      embedding_dimension: 1
    - statistic: mean
      embedding_dimension: 10
    - statistic: max
      embedding_dimension: 10
    - statistic: diff
      embedding_dimension: 10

# Information-theoretic statistics
.statistics.infotheory:

  joint_entropy: # No theiler window yet

    - estimator: gaussian

    - estimator: kozachenko

    - estimator: kernel

  conditional_entropy: # No theiler window yet

    - estimator: gaussian

    - estimator: kozachenko

    - estimator: kernel

  causal_entropy: # No theiler window yet

    - estimator: gaussian

    - estimator: kozachenko

    - estimator: kernel

  crossmap_entropy: # No theiler window yet

    - estimator: gaussian
      history_length: 1

    - estimator: kozachenko
      history_length: 1

    - estimator: kernel
      history_length: 1


    - estimator: gaussian
      history_length: 10

    - estimator: kozachenko
      history_length: 10

    - estimator: kernel
      history_length: 10

  directed_info: # No theiler window yet

    - estimator: gaussian

    - estimator: kozachenko

    - estimator: kernel

  stochastic_interaction: # No theiler window

    - estimator: gaussian

    - estimator: kozachenko

    - estimator: kernel

  # Mutual information
  mutual_info:
    - estimator: gaussian

    - estimator: kraskov
      prop_k: 4

    - estimator: kraskov
      prop_k: 4
      dyn_corr_excl: AUTO

    - estimator: kernel
      kernel_width: 0.25

# Mutual information
  time_lagged_mutual_info:
    - estimator: gaussian

    - estimator: kraskov
      prop_k: 4

    - estimator: kraskov
      prop_k: 4
      dyn_corr_excl: AUTO

    - estimator: kernel
      kernel_width: 0.25

  # Transfer entropy
  transfer_entropy:

    # Kraskov estimator with auto-embedding on source/target and DCE
    - estimator: kraskov
      prop_k: 4
      auto_embed_method: MAX_CORR_AIS
      k_search_max: 10
      tau_search_max: 4

    - estimator: kraskov
      prop_k: 4
      auto_embed_method: MAX_CORR_AIS
      k_search_max: 10
      tau_search_max: 4
      dyn_corr_excl: AUTO

    # Kraskov estimator with auto-embedding on target-only, src history of 1, and DCE
    - estimator: kraskov
      prop_k: 4
      k_history: 2
      l_history: 1
      dyn_corr_excl: AUTO

    # Kraskov estimator with fixed embedding of 1 for source/target and DCE
    - estimator: kraskov
      prop_k: 4
      k_history: 1
      l_history: 1
      dyn_corr_excl: AUTO
    
    # Same as above with no DCE
    - estimator: kraskov
      prop_k: 4
      k_history: 1
      l_history: 1

    # Currently the Kernel method has an overload issue with the AIS calculator..
    # Kernel estimator with auto-embedding on source/target and DCE
    # - estimator: kernel
    #   auto_embed_method: MAX_CORR_AIS
    #   k_search_max: 4
    #   kernel_width: 0.25

    # Kernel estimator with no auto-embedding on source/target and DCE
    - estimator: kernel
      kernel_width: 0.25
      k_history: 1
      l_history: 1

    # Gaussian estimator doesn't have DCE (aka Bartlett corrections) yet
    - estimator: gaussian
      auto_embed_method: MAX_CORR_AIS
      k_search_max: 10
      tau_search_max: 2

    - estimator: gaussian
      k_history: 1
      l_history: 1

    - estimator: symbolic
      k_history: 1
      l_history: 1

    - estimator: symbolic
      k_history: 10
      l_history: 1

  integrated_information:
    - phitype: 'star'

    - phitype: 'star'
      normalization: 1

    - phitype: 'Geo'

    - phitype: 'Geo'
      normalization: 1

# statistics that analyse in the frequency-domain (see Schoegl and Supp, 2006)
.statistics.spectral:

  coherence_phase:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  coherence_magnitude:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  # Coherence (ordinal or squared? imaginary components of the coherence)
  icoherence:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  phase_slope_index:
    - fmin: 0
      fmax: 0.5

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

  phase_locking_value:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  phase_lag_index:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  weighted_phase_lag_index:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  debiased_squared_phase_lag_index:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  debiased_squared_weighted_phase_lag_index:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  pairwise_phase_consistency:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  directed_transfer_function:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max
      
  # partial_coherence:
  #   - fs: 1

  #   - fmin: 0
  #     fmax: 0.25

  #   - fmin: 0.25
  #     fmax: 0.5

  #   - fs: 1
  #     statistic: max

  #   - fmin: 0
  #     fmax: 0.25
  #     statistic: max

  #   - fmin: 0.25
  #     fmax: 0.5
  #     statistic: max

  directed_coherence:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  partial_directed_coherence:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  generalized_partial_directed_coherence:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  direct_directed_transfer_function:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fs: 1
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

  group_delay:
    - fmin: 0
      fmax: 0.5
      statistic: delay

    - fmin: 0
      fmax: 0.25
      statistic: delay

    - fmin: 0.25
      fmax: 0.5
      statistic: delay

  spectral_granger:
      # Non-parametric Granger causality (no VAR model)
    - method: nonparametric
      fmin: 0
      fmax: 0.5
      statistic: mean

    - method: nonparametric
      fmin: 0
      fmax: 0.25
      statistic: mean

    - method: nonparametric
      fmin: 0.25
      fmax: 0.5
      statistic: mean

    - method: nonparametric
      fmin: 0
      fmax: 0.5
      statistic: max

    - method: nonparametric
      fmin: 0
      fmax: 0.25
      statistic: max

    - method: nonparametric
      fmin: 0.25
      fmax: 0.5
      statistic: max

      # Parametric Granger causality (VAR model with inferred or predefined order)

      # AR order optimised by BIC
    - method: parametric
      fmin: 0
      fmax: 0.5
      statistic: mean

    - method: parametric
      fmin: 0
      fmax: 0.25
      statistic: mean

    - fmin: 0.25
      fmax: 0.5
      method: parametric
      statistic: mean

      # AR order 1
    - fs: 1
      order: 1
      method: parametric
      statistic: mean

    - fmin: 0
      fmax: 0.25
      order: 1
      method: parametric
      statistic: mean

    - fmin: 0.25
      fmax: 0.5
      order: 1
      method: parametric
      statistic: mean

      # AR order 20
    - fs: 1
      order: 20
      method: parametric
      statistic: mean

    - fmin: 0
      fmax: 0.25
      order: 20
      method: parametric
      statistic: mean

    - fmin: 0.25
      fmax: 0.5
      order: 20
      method: parametric
      statistic: mean

      # AR order optimised by BIC
    - fs: 1
      method: parametric
      statistic: max

    - fmin: 0
      fmax: 0.25
      method: parametric
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      method: parametric
      statistic: max

      # AR order 1
    - fs: 1
      order: 1
      method: parametric
      statistic: max

    - fmin: 0
      fmax: 0.25
      order: 1
      method: parametric
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      order: 1
      method: parametric
      statistic: max

      # AR order 20
    - fs: 1
      order: 20
      method: parametric
      statistic: max

    - fmin: 0
      fmax: 0.25
      order: 20
      method: parametric
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      order: 20
      method: parametric
      statistic: max

  # Power envelope correlation
  envelope_correlation:
    - orth: False
      log: False
      absolute: False

    - orth: True
      log: False
      absolute: False

    - orth: False
      log: True
      absolute: False

    - orth: True
      log: True
      absolute: False

    - orth: True
      log: False
      absolute: True

    - orth: True
      log: True
      absolute: True

# statistics that analyse in the wavlet-domain (only Mortlet wavelet's at the moment)
.statistics.wavelet:

  # coherence_magnitude:
  #   - fs: 1

  #   - fmin: 0
  #     fmax: 0.25

  #   - fmin: 0.25
  #     fmax: 0.5

  #   - fs: 1
  #     statistic: max

  #   - fmin: 0
  #     fmax: 0.25
  #     statistic: max

  #   - fmin: 0.25
  #     fmax: 0.5
  #     statistic: max

  # coherence_phase:
  #   - fs: 1

  #   - fmin: 0
  #     fmax: 0.25

  #   - fmin: 0.25
  #     fmax: 0.5

  #   - fs: 1
  #     statistic: max

  #   - fmin: 0
  #     fmax: 0.25
  #     statistic: max

  #   - fmin: 0.25
  #     fmax: 0.5
  #     statistic: max

  # # Coherence (ordinal or squared? imaginary components of the coherence)
  # icoherence:
  #   - fs: 1

  #   - fmin: 0
  #     fmax: 0.25

  #   - fmin: 0.25
  #     fmax: 0.5

  #   - fs: 1
  #     statistic: max

  #   - fmin: 0
  #     fmax: 0.25
  #     statistic: max

  #   - fmin: 0.25
  #     fmax: 0.5
  #     statistic: max

  # phase_locking_value:
  #   - fs: 1

  #   - fmin: 0
  #     fmax: 0.25

  #   - fmin: 0.25
  #     fmax: 0.5

  #   - fs: 1
  #     statistic: max

  #   - fmin: 0
  #     fmax: 0.25
  #     statistic: max

  #   - fmin: 0.25
  #     fmax: 0.5
  #     statistic: max

  # pairwise_phase_consistency:
  #   - fs: 1

  #   - fmin: 0
  #     fmax: 0.25

  #   - fmin: 0.25
  #     fmax: 0.5

  #   - fs: 1
  #     statistic: max

  #   - fmin: 0
  #     fmax: 0.25
  #     statistic: max

  #   - fmin: 0.25
  #     fmax: 0.5
  #     statistic: max

  # phase_lag_index:
  #   - fs: 1

  #   - fmin: 0
  #     fmax: 0.25

  #   - fmin: 0.25
  #     fmax: 0.5

  #   - fs: 1
  #     statistic: max

  #   - fmin: 0
  #     fmax: 0.25
  #     statistic: max

  #   - fmin: 0.25
  #     fmax: 0.5
  #     statistic: max

  # debiased_squared_phase_lag_index:
  #   - fs: 1

  #   - fmin: 0
  #     fmax: 0.25

  #   - fmin: 0.25
  #     fmax: 0.5

  #   - fs: 1
  #     statistic: max

  #   - fmin: 0
  #     fmax: 0.25
  #     statistic: max

  #   - fmin: 0.25
  #     fmax: 0.5
  #     statistic: max

  # weighted_phase_lag_index:
  #   - fs: 1

  #   - fmin: 0
  #     fmax: 0.25

  #   - fmin: 0.25
  #     fmax: 0.5

  #   - fs: 1
  #     statistic: max

  #   - fmin: 0
  #     fmax: 0.25
  #     statistic: max

  #   - fmin: 0.25
  #     fmax: 0.5
  #     statistic: max

  # debiased_weighted_squared_phase_lag_index:
  #   - fs: 1

  #   - fmin: 0
  #     fmax: 0.25

  #   - fmin: 0.25
  #     fmax: 0.5

  #   - fs: 1
  #     statistic: max

  #   - fmin: 0
  #     fmax: 0.25
  #     statistic: max

  #   - fmin: 0.25
  #     fmax: 0.5
  #     statistic: max

  phase_slope_index:
    - fs: 1

    - fmin: 0
      fmax: 0.25

    - fmin: 0.25
      fmax: 0.5

    - fmin: 0
      fmax: 0.5
      statistic: max

    - fmin: 0
      fmax: 0.25
      statistic: max

    - fmin: 0.25
      fmax: 0.5
      statistic: max

.statistics.misc:

  linearmodel:
    - model: Ridge
    - model: Lasso
    - model: SGDRegressor
    - model: ElasticNet
    - model: BayesianRidge

  gpmodel:
    - kernel: DotProduct
    - kernel: RBF


  # Cointegration
  coint:
    - method: johansen
      statistic: max_eig_stat
      det_order: 0 # Constant trend
      k_ar_diff: 10

    - method: johansen
      statistic: trace_stat
      det_order: 0
      k_ar_diff: 10

    - method: johansen
      statistic: max_eig_stat
      det_order: 0 # Constant trend
      k_ar_diff: 1

    - method: johansen
      statistic: trace_stat
      det_order: 0
      k_ar_diff: 1

    - method: johansen
      statistic: max_eig_stat
      det_order: 1 # Linear trend
      k_ar_diff: 10

    - method: johansen
      statistic: trace_stat
      det_order: 1
      k_ar_diff: 10

    - method: johansen
      statistic: max_eig_stat
      det_order: 1
      k_ar_diff: 1

    - method: johansen
      statistic: trace_stat
      det_order: 1
      k_ar_diff: 1

    - method: aeg
      statistic: tstat
      autolag: aic
      maxlag: 10
      trend: c

    - method: aeg
      statistic: tstat
      autolag: aic
      maxlag: 10
      trend: ct

    - method: aeg
      statistic: tstat
      autolag: bic
      maxlag: 10
      trend: ct