# Pearson and Spearman correlation statistics
.statistics.basic:
  # Covariance
  Covariance:
    labels:
      - undirected
      - nonlinear
      - unisgned
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - estimator: EmpiricalCovariance

  # Spearman's correlation coefficient
  SpearmanR:
    labels:
      - undirected
      - nonlinear
      - signed
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - squared: True

# Directed information with a Gaussian density estimator
.statistics.infotheory:
  DirectedInfo:
    labels:
      - directed
      - nonlinear
      - unsigned
      - bivariate
      - time-dependent
    dependencies:
      - java
    configs:
      - estimator: gaussian

# Power envelope correlation
.statistics.misc:
  PowerEnvelopeCorrelation:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - orth: False
        log: False
        absolute: False
