# Correlation-based measures
.correlation:

  # Pearson's product-moment correlation coefficient
  pearsonr:
    - cov_estimator: empirical

    - cov_estimator: empirical
      squared: True

    - cov_estimator: ledoit_wolf

    - cov_estimator: shrunk

    - cov_estimator: oas

  # Partial correlation
  pcor:
    - cov_estimator: empirical

    - cov_estimator: empirical
      squared: True

    - cov_estimator: ledoit_wolf

    - cov_estimator: shrunk

    - cov_estimator: oas

  # Precision
  precision:
    - cov_estimator: empirical
      squared: False

    - cov_estimator: empirical
      squared: True

  # Spearman's correlation coefficient
  spearmanr:
    - squared: True

    - squared: False

  # Kendall's rank correlation coefficient
  kendalltau:
    - squared: True

    - squared: False

  # Measures based on cross-correlation (squared means we square the xcorr, not the output)
  xcorr:
    - statistic: 'max'

    - statistic: 'max'
      squared: True
  
    - statistic: 'mean'

    - statistic: 'mean'
      squared: True

  # Distance correlation
  dcorr:

  # Multi-scale graph correlation
  mgc:

  # Hilbert-Schmidt independence criterion
  hsic:

  # Heller-Heller-Gorfine (HHG) test  
  hhg:

.causal:

  # Additive noise model
  anm:

  gpfit:

  cds:

  # gnn:

  igci:

  reci:

  
# Measures that analyse in the time-domain
.temporal:

  # Cointegration
  coint:
    - method: johansen
      statistic: max_eig_stat

    - method: johansen
      statistic: trace_stat

    - method: aeg
      statistic: tstat

    - method: aeg
      statistic: pvalue

  # Convergent-cross mapping
  ccm:
    - statistic: mean
    - statistic: max
    - statistic: diff

  # Multi-scale graph correlation for time series
  mgcx:
    - max_lag: 5

  # Distance correlation for time series
  dcorrx:
    - max_lag: 5

# Measures that analyse in the frequency-domain (see Schoegl and Supp, 2006)
.spectral:

  # Coherence (ordinal or squared? real components of the coherence)
  coherency:

  coherence_phase:

  coherence_magnitude:

  # Coherence (ordinal or squared? imaginary components of the coherence)
  icoherence:

  phase_slope_index:

  phase_locking_value:

  phase_lag_index:

  weighted_phase_lag_index:

  debiased_squared_phase_lag_index:

  debiased_squared_weighted_phase_lag_index:

  pairwise_phase_consistency:

  directed_transfer_function:

  directed_coherence:

  partial_directed_coherence:

  generalized_partial_directed_coherence:

  direct_directed_transfer_function:

  group_delay:
    
  spectral_granger:
    - fs: 1

    - fs: 1
      order: 1

    - fs: 1
      order: 20

# Information-theoretic measures
.infotheory:

  conditional_entropy: # No theiler window yet

    - estimator: gaussian

    - estimator: kozachenko

    - estimator: kernel

  causal_entropy: # No theiler window yet

    - estimator: gaussian

    - estimator: kozachenko

    - estimator: kernel

  directed_info: # No theiler window yet

    - estimator: gaussian

    - estimator: kozachenko

    - estimator: kernel

  stochastic_interaction: # No theiler window

    - estimator: gaussian

    - estimator: kozachenko

    - estimator: kernel

  # Mutual information
  mutual_info:
    - estimator: gaussian

    - estimator: kraskov
      prop_k: 4

    - estimator: kraskov
      prop_k: 4
      dyn_corr_excl: AUTO

    - estimator: kernel
      kernel_width: 0.25

# Mutual information
  time_lagged_mutual_info:
    - estimator: gaussian

    - estimator: kraskov
      prop_k: 4

    - estimator: kraskov
      prop_k: 4
      dyn_corr_excl: AUTO

    - estimator: kernel
      kernel_width: 0.25

  # Transfer entropy
  transfer_entropy:

    # Kraskov estimator with auto-embedding on source/target and DCE
    - estimator: kraskov
      prop_k: 4
      auto_embed_method: MAX_CORR_AIS
      k_search_max: 10
      tau_search_max: 4
      dyn_corr_excl: AUTO

    - estimator: kraskov
      prop_k: 4
      auto_embed_method: MAX_CORR_AIS
      k_search_max: 10
      tau_search_max: 1
      dyn_corr_excl: AUTO

    # Kraskov estimator with auto-embedding on target-only, src history of 1, and DCE
    - estimator: kraskov
      prop_k: 4
      k_history: 2
      l_history: 1
      dyn_corr_excl: AUTO

    # Kraskov estimator with fixed embedding of 1 for source/target and DCE
    - estimator: kraskov
      prop_k: 4
      k_history: 1
      l_history: 1
      dyn_corr_excl: AUTO
    
    # Same as above with no DCE
    - estimator: kraskov
      prop_k: 4
      k_history: 1
      l_history: 1

    # Currently the Kernel method has an overload issue with the AIS calculator..
    # Kernel estimator with auto-embedding on source/target and DCE
    # - estimator: kernel
    #   auto_embed_method: MAX_CORR_AIS
    #   k_search_max: 4
    #   kernel_width: 0.25

    # Kernel estimator with no auto-embedding on source/target and DCE
    - estimator: kernel
      kernel_width: 0.25
      k_history: 1
      l_history: 1

    # Gaussian estimator doesn't have DCE (aka Bartlett corrections) yet
    - estimator: gaussian
      auto_embed_method: MAX_CORR_AIS
      k_search_max: 10
      tau_search_max: 2

    - estimator: gaussian
      k_history: 1
      l_history: 1