# Correlation-based measures
.correlation:

  # Pearson's product-moment correlation coefficient
  pearsonr:
    - cov_estimator: empirical

    - cov_estimator: empirical
      squared: True

    - cov_estimator: ledoit_wolf

    - cov_estimator: shrunk

    - cov_estimator: oas

  # Partial correlation
  pcor:
    - cov_estimator: empirical

    - cov_estimator: empirical
      squared: True

    - cov_estimator: ledoit_wolf

    - cov_estimator: shrunk

    - cov_estimator: oas

  # Covariance
  covariance:
    - cov_estimator: empirical

  # Precision
  precision:
    - cov_estimator: empirical
      squared: False

    - cov_estimator: empirical
      squared: True

  # Spearman's correlation coefficient
  spearmanr:
    - squared: True

    - squared: False

  # Kendall's rank correlation coefficient
  kendalltau:
    - squared: True

    - squared: False

  # Distance correlation
  dcorr:

  # Multi-scale graph correlation
  mgc:

  # Hilbert-Schmidt independence criterion
  hsic:

  # Heller-Heller-Gorfine (HHG) test  
  hhg:
  
# Measures that analyse in the time-domain
.temporal:

  # Cointegration
  coint:
    - method: johansen
      statistic: max_eig_stat

    - method: johansen
      statistic: trace_stat

    - method: aeg
      statistic: tstat

    - method: aeg
      statistic: pvalue

  # Convergent-cross mapping
  ccm:
    - statistic: mean
    - statistic: max
    - statistic: diff

  # Multi-scale graph correlation for time series
  mgcx:
    - max_lag: 5

  # Distance correlation for time series
  dcorrx:
    - max_lag: 5

# Measures that analyse in the frequency-domain (see Schoegl and Supp, 2006)
.spectral:

  # Cross-spectrum
  # spectrum:

  # Coherence (ordinal or squared? real components of the coherence)
  coherence:
    - f_lb: 0.0
      f_ub: 0.2

    - f_lb: 0.02
      f_ub: 10

  # Coherence (ordinal or squared? imaginary components of the coherence)
  icoherence:

  # Phase difference of signals relative to one another
  phase:

  # Phase lag
  phase_lag:

  # Weighted phase lag
  weighted_phase_lag:

  # De-biased squared weighted phase lag
  debiased_squared_weighted_phase_lag:

  # Partial coherence (condition out all other processes)
  partial_coherence:

  ## These two get seg faults sometimes?
  partial_directed_coherence:

  directed_transfer_function:
    
  # Spectral granger causality
  spectral_granger:
    - fs: 1

    - fs: 1
      order: 1

    - fs: 1
      order: 20

# Information-theoretic measures
.infotheory:

  # Mutual information
  mutual_info:
    - estimator: gaussian

    - estimator: kraskov
      prop_k: 4

    - estimator: kraskov
      prop_k: 4
      dyn_corr_excl: AUTO

    - estimator: kernel
      kernel_width: 0.25

# Mutual information
  time_lagged_mutual_info:
    - estimator: gaussian

    - estimator: kraskov
      prop_k: 4

    - estimator: kraskov
      prop_k: 4
      dyn_corr_excl: AUTO

    - estimator: kernel
      kernel_width: 0.25

  # Transfer entropy
  transfer_entropy:

    # Kraskov estimator with auto-embedding on source/target and DCE
    - estimator: kraskov
      prop_k: 4
      auto_embed_method: MAX_CORR_AIS
      k_search_max: 10
      tau_search_max: 4
      dyn_corr_excl: AUTO

    - estimator: kraskov
      prop_k: 4
      auto_embed_method: MAX_CORR_AIS
      k_search_max: 10
      tau_search_max: 1
      dyn_corr_excl: AUTO

    # Kraskov estimator with auto-embedding on target-only, src history of 1, and DCE
    - estimator: kraskov
      prop_k: 4
      k_history: 2
      l_history: 1
      dyn_corr_excl: AUTO

    # Kraskov estimator with fixed embedding of 1 for source/target and DCE
    - estimator: kraskov
      prop_k: 4
      k_history: 1
      l_history: 1
      dyn_corr_excl: AUTO
    
    # Same as above with no DCE
    - estimator: kraskov
      prop_k: 4
      k_history: 1
      l_history: 1

    # Kernel estimator with auto-embedding on source/target and DCE
    - estimator: kernel
      auto_embed_method: MAX_CORR_AIS
      k_search_max: 4
      kernel_width: 0.25

    # Kernel estimator with no auto-embedding on source/target and DCE
    - estimator: kernel
      kernel_width: 0.25
      k_history: 1
      l_history: 1

    # Gaussian estimator doesn't have DCE (aka Bartlett corrections) yet
    - estimator: gaussian
      auto_embed_method: MAX_CORR_AIS
      k_search_max: 10
      tau_search_max: 2

    - estimator: gaussian
      k_history: 1
      l_history: 1