name: Run Unit Test via PyTest

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install octave
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential octave
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

