name: Windows Runner

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Octave
      run: |
        choco install octave --version 8.3.0.20230817 -y